### ISSUE TITLE
Upload ndl2 and provide a link

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#100]
After uploading ndl2 to github add the link to the repository in the readme.

**Comment by Trybnetic** [comment]
ndl2 is now available [here](https://github.com/quantling/ndl2). We should add links to it either in the [readme](https://github.com/quantling/pyndl/blob/main/README.rst) (but I am not sure where) and in the documentation  (for example, but not limited to, [here](https://pyndl.readthedocs.io/en/latest/credits.html#acknowledgements)). I leave the issue open until the links are added.
