### ISSUE TITLE
packageing python package

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#11]
Useful links

* official python documentation https://packaging.python.org/
* conda http://conda.pydata.org/docs/building/build.html
* https://www.pypa.io/en/latest/

Overviews:

* https://vladcalin.github.io/what-every-python-project-should-have.html
* https://github.com/SethMichaelLarson/python_project_template
* https://blog.emacsos.com/bootstrap-a-python-project.html

**Comment by Trybnetic** [comment]
As the package now is on [PyPi](https://pypi.python.org/), I assume this Issue can be closed.
