### ISSUE TITLE
Use copybutton.js for documentation

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#114]
Copybutton.js needs to be integrated into the sphinx theme.

We have to take care of the license most likely as in `scipy-sphinx-theme`

https://github.com/scipy/scipy-sphinx-theme/blob/master/_theme/scipy/static/js/copybutton.js

https://github.com/scipy/scipy-sphinx-theme/blob/master/LICENSE.txt

Alternatively, we could use the scipy-sphinx-theme.

**Comment by derNarr** [comment]
Alternative theme, which might look good, is:

https://cloud-sptheme.readthedocs.io/en/latest/cloud_theme_test.html

**Comment by Trybnetic** [comment]
There is also the possibility adding a copybutton using [easydev](https://pythonhosted.org/easydev/quickstart.html) as described [here](http://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#copybutton).
