### ISSUE TITLE
Mac OS X vs macos vs macOS

### ISSUE THREAD

**Issue by Trybnetic** [quantling/pyndl#125]
As @dekuenstle pointed out in #112 apple's operating system can be written in many different ways. Currently, we use Mac OS X which might be legacy.

Which way to write it should be used?

- Mac OS X
- macos
- macOS

**Comment by dekuenstle** [comment]
The company website writes it as *macOS* in the current version. I think we should do it the same way.
Mac OS X is legacy, but I think people still understand what's meant.
