### ISSUE TITLE
More comprehensive description of NDL

### ISSUE THREAD

**Issue by Trybnetic** [quantling/pyndl#133]
We should overwork the text of `doc/source/ndl.rst` and make it more comprehensive.

@dekuenstle suggested the following points:
* add references about the learning rule and the matrix implementation
* add a quick note about equilibruum solutions
* make the terminology more precise
* Synchronize equations of RW or explain why and how

**Comment by derNarr** [comment]
Decide if we want to stick closer to the 'classical conditioning' terminology with (conditioned / unconditioned) stimulus and (conditioned / unconditioned) response or if we want to have our own terminology or a terminology which is inspired by machine learning techniques.

**Comment by derNarr** [comment]
The terminology of `cues` and `outcomes` and `events` seemed to have worked for our lab in the last years. If someone opens a pull request with a concrete suggestion and puts the work in to reword the chapter, I will have a look on it. But for now I close this issue.
