### ISSUE TITLE
Bug: Event order not guaranteed

### ISSUE THREAD

**Issue by dekuenstle** [quantling/pyndl#149]
### What you were trying to do
In the ndl function events are transformed to multiple binary files.
The files of the binary events should be processed in the order of the events in the original event file.

### What actually happened
File paths are processed in arbitrary order.
See [the relevant code line](https://github.com/quantling/pyndl/blob/38e76b72cd1ea73fb6a38766ed4ff3f4327f88cd/pyndl/ndl.py#L170) and [docs of os.listdir](https://docs.python.org/3/library/os.html#os.listdir):

```python3
binary_files = [os.path.join(binary_path, binary_file)
                        for binary_file in os.listdir(binary_path)
                        if os.path.isfile(os.path.join(binary_path, binary_file))]
```

> *os.listdir ...* Return a list containing the names of the entries in the directory given by path. The list is in arbitrary order, ...

### System details
Should apply on all pyndl and python3 versions.

**Comment by derNarr** [comment]
I would really like to have a test in the test suite that fails, if the order is not correct. I suggest a fix for this problem. In a pull request.

I don't understand, why it is not yet discovered. Did we always only had one binary event file in the test cases?
