### ISSUE TITLE
subsitute landscape.io with lgtm.com?

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#175]
landscape.io seems to be not very alive any more:

- https://docs.landscape.io/faq.html (404)
- last twitter 2 years old (https://twitter.com/landscapeio)

This seems to be also discovered here:

  https://github.com/scikit-learn/scikit-learn/issues/3888

We should switch to lgtm.com or remove the service without replacement.

What do you think?

**Comment by derNarr** [comment]
In order to replace the two ci services we should exchange the badges and change the https://pyndl.readthedocs.io/en/latest/development.html source rst file.

**Comment by Trybnetic** [comment]
Switching to lgtm.com seems a good idea for me. Some kind of code quality monitoring is a nice think to have in my opinion.

**Comment by dekuenstle** [comment]
Yes, static code analysis is very useful. I've also seen projects using https://www.codacy.com/ , but I don't have a favorite.

**Comment by Trybnetic** [comment]
If I understand codacy correctly, it probably could also replace coveralls as it advertises that it also provides code coverage.
