### ISSUE TITLE
ndl_parallel causes an error on macOS

### ISSUE THREAD

**Issue by striatum** [quantling/pyndl#181]
### What you were trying to do

```
from pyndl.ndl import ndl
```

### What actually happened

	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/Library/Frameworks/Python.framework/anaconda3/lib/python3.7/site-packages/pyndl/ndl.py", line 28, in <module>
	    from . import ndl_parallel
	ImportError: dlopen(/Library/Frameworks/Python.framework/anaconda3/lib/python3.7/site-packages/pyndl/ndl_parallel.cpython-37m-darwin.so, 2): Symbol not found: _GOMP_loop_nonmonotonic_dynamic_next
	  Referenced from: /Library/Frameworks/Python.framework/anaconda3/lib/python3.7/site-packages/pyndl/ndl_parallel.cpython-37m-darwin.so
	  Expected in: flat namespace
	 in /Library/Frameworks/Python.framework/anaconda3/lib/python3.7/site-packages/pyndl/ndl_parallel.cpython-37m-darwin.so

### System details

> Pyndl Information
> =================
> 
> General Information
> -------------------
> Python version: 3.7.4
> Pyndl version: 0.6.4
> 
> Operating System
> ----------------
> OS: Darwin x86_64
> Kernel: 18.7.0
> CPU: 12
> 
> Dependencies
> ------------
> pip: 20.0.2
> numpy: 1.18.1
> cython: 0.29.15
> xarray: 0.14.1
> netCDF4: 1.5.3
> pandas: 1.0.1

**Comment by derNarr** [comment]
Hi,

as your ``pyndl`` version is still on ``0.6.4`` this is the expected behaviour.

Please run the following command and check if the error is gone::

  pip install -U pyndl

If not please update what kind of error occurs. The Mac install should be fixed with the ``0.7.0`` version of pyndl.

Thanks!

**Comment by derNarr** [comment]
Is this fixed now? If not, please reopen.
