### ISSUE TITLE
List of changes to consider

### ISSUE THREAD

**Issue by striatum** [quantling/pyndl#184]
> [Note: Tino suggested me to list them here!]

The suggested changes concern the functions `activation()` from the **activation** module, `create_event_file()` and `filter_event_file()` from the **preprocess** module, and `ndl()` from the **ndl** module:

1. Activation:
    + Running with multiple cores doesn’t make the training faster than with one core but actually can make it slightly slower. It seems that `_activation_matrix()` chokes.
    + One suggestion to make things run even faster (even with one core) is to generate batches of events as a matrix and convert to activations using matrix multiplication; i.e., sparse *document-to-term*-like matrix with events in the rows and cues in the columns multiplied by the weight matrix.

2. Reasonable compatibility with MS Windows can be achieved with minimal efforts. A couple of problems that we have detected and which can be easily fixed are:
    + Adding `encoding = 'utf8'` whenever they read or write to a text file. Alternatively, add an argument `encoding` at the top of the functions to let the user choose the encoding. Maybe also allow the user to choose the separator between lines rather than just use `'\t'`.
    + On MS Windows, running `activation()` with multi-threading doesn’t work. You get this error message:
        > "python` windows _pickle.PicklingError: Can't pickle <class 'c_double_Array>".
3. Compatibility with macOS:
    + When using `ndl.ndl()`, `method = 'openmp'` doesn’t work and one can only use `method = 'threading'`. We suggest adding a command line where they detect whether the system is a macOS or not; e.g., something like `if sys.platform == 'darwin'`. Then automatically switch to threading if you have a macOS user.

**Comment by derNarr** [comment]
Hi, thanks for letting me know this.

For 1. I have to look into that. Elnaz might have some suggestions on that as well.

For 2. this is a good suggestion. I set up a Windows VM on my machine so that I can test where to specify the encoding. I would go with utf-8 for now and keep the ``\t`` delimiter. But if there is real need, we can make it a keyword argument as well at some point.

For 3.: Would changing the default to ``threading`` already solve this for you? Then you have to explicitly specify ``method=openmp`` to get the error message.

**Comment by striatum** [comment]
- [2] using utf-8 and `\t` sounds great; keep me posted
- [3] `threading` as the default is also reasonable

Thanks!

**Comment by striatum** [comment]
- [2] using utf-8 and `\t` sounds great; keep me posted
- [3] `threading` as the default is also reasonable

Thanks!

**Comment by striatum** [comment]
- [2] using utf-8 and `\t` sounds great; keep me posted
- [3] `threading` as the default is also reasonable

Thanks!

**Comment by striatum** [comment]
- [ ] using utf-8 and `\t` sounds great; keep me posted
- [ ] `threading` as the default is also reasonable

Thanks!

**Comment by striatum** [comment]
- [ ] using utf-8 and `\t` sounds great; keep me posted
- [ ] `threading` as the default is also reasonable

Thanks!

**Comment by striatum** [comment]
- [ ] using utf-8 and `\t` sounds great; keep me posted
- [ ] `threading` as the default is also reasonable

Thanks!

**Comment by striatum** [comment]
- [ ] using utf-8 and `\t` sounds great; keep me posted
- [ ] `threading` as the default is also reasonable

Thanks!

**Comment by striatum** [comment]
- [ ] using utf-8 and `\t` sounds great; keep me posted
- [ ] `threading` as the default is also reasonable

Thanks!
