### ISSUE TITLE
more instructions on installing gcc in docs

### ISSUE THREAD

**Issue by MegamindHenry** [quantling/pyndl#187]
### What you were trying to do

installing pyndl on MacOS, Win10 and Debian

### What actually happened

we need more instructions on MacOS, Win10 and Debian on how to install gcc first

### How to reproduce

* Step 1
* Step 2
* Step 3

**Comment by derNarr** [comment]
Hi @MegamindHenry ,

`pyndl` requires `Cython` to be installed properly with the ability to compile Cython extensions for Python. Depending on how you install `Cython` manually adding the Python header files (on Debian with `sudo apt-get install python-dev`) and adding `gcc` (on Debian through the `build-essential` package with `sudo apt-get install build-essential`) is a necessary step of this. If you use scientific Python distribution like Miniconda, running `conda install cython` should take care of all these steps.

With the next version of `pyndl` we will clarify this in the documentation. Thank you for you hint and sorry for the late response. Note that on MacOS having `clang` installed should be enough to compile the extensions in the recent versions of `pyndl`.

Kind regards, Tino
