### ISSUE TITLE
Improve wh documentation

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#208]
We should improve the documentation of the WH code in the following way:

- [x] check that all docstrings are consistent with the rest of the docstrings
- [x] add an example to the documentation
- [ ] check that all docstrings are well readable on readthedocs
- [ ] optionally add an extra chapter on WH and which terminology we use

I tend to not add an extra chapter, but will discuss this with my colleagues.

**Comment by derNarr** [comment]
This is addressed in a first PR #207

**Comment by frankier** [comment]
I think this should be completed for the JOSS paper, since this functionality is mentioned there, but it appears to still only be partially documented.
