### ISSUE TITLE
module `pandas` has no attribute `Panel`

### ISSUE THREAD

**Issue by striatum** [quantling/pyndl#210]
### What you were trying to do

Standard training that used to work a week or two ago. The relevant bits of code are:

    from pyndl.ndl import ndl
    
    weights = ndl(
        EVENTS,
        alpha=1, betas=(0.01, 0.01),
        number_of_threads=NUMBER_OF_PROCESSES,
        remove_duplicates=True,
        verbose=True)
    weights.to_netcdf(MATRIX_FILE)

### What actually happened

Soon after submitting a job, the error returns. I believe that the process does not even start but only the initial parts. This is the message:

>    from pyndl.ndl import ndl
>   File "/rds/homes/m/milinp/.local/lib/python3.7/site-packages/pyndl/ndl.py", line 24, in <module>
>     import xarray as xr
>   File "/rds/homes/m/milinp/miniconda3/envs/petar/lib/python3.7/site-packages/xarray/__init__.py", line 11, in <module>
>     from .core.combine import combine_by_coords, combine_nested, auto_combine
>   File "/rds/homes/m/milinp/miniconda3/envs/petar/lib/python3.7/site-packages/xarray/core/combine.py", line 8, in <module>
>     from .dataarray import DataArray
>   File "/rds/homes/m/milinp/miniconda3/envs/petar/lib/python3.7/site-packages/xarray/core/dataarray.py", line 12, in <module>
>     from . import (
>   File "/rds/homes/m/milinp/miniconda3/envs/petar/lib/python3.7/site-packages/xarray/core/computation.py", line 17, in <module>
>     from .merge import expand_and_merge_variables
>   File "/rds/homes/m/milinp/miniconda3/envs/petar/lib/python3.7/site-packages/xarray/core/merge.py", line 18, in <module>
>     PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
>   File "/rds/homes/m/milinp/miniconda3/envs/petar/lib/python3.7/site-packages/pandas/__init__.py", line 244, in __getattr__
>     raise AttributeError(f"module 'pandas' has no attribute '{name}'")
> AttributeError: module 'pandas' has no attribute 'Panel'

### System details

General Information
-------------------
Python version: 3.7.13
Pyndl version: 0.8.1

Operating System
----------------
OS: Linux x86_64
Kernel: 4.18.0-348.2.1.el8_5.x86_64
CPU: 8
Mem: 18531MiB/62811MiB
Swap: 6252MiB/32767MiB

**Comment by striatum** [comment]
There were some issues with `xarray` but that was resolved. One possibility is to downgrade `pandas`.

**Comment by striatum** [comment]
A proposed temporary solution:

    conda uninstall pandas
    conda install -c conda-forge pandas=0.24

**Comment by derNarr** [comment]
Hi, sorry for the late reply.

Instead of downgrading ``pandas`` it might be possible to upgrade ``xarray`` to the newest version with:

```
pip install -U xarray
```
You should have version ``'2022.3.0'`` for ``xarray``. You can check this with:

```
python -c "import xarray; print(xarray.__version__)"
```

Does this solves you issue as well?

**Comment by striatum** [comment]
`xarray` version: 0.18.0
`pandas` version: 1.3.4

> Does this solves you issue as well?

I will start testing and report back.

**Comment by Trybnetic** [comment]
I assume this issue has been resolved. If not, feel free to open it again.
