### ISSUE TITLE
create_event_file does not deal with accented characters(?)

### ISSUE THREAD

**Issue by frankier** [quantling/pyndl#220]
### What you were trying to do

Run the following code:

```
from pyndl import preprocess

CORPUS = """
mitä
mikä
minä
miksi
""".strip()

with open("/tmp/corpus.txt", "w") as f:
    f.write(CORPUS)

if os.path.exists("/tmp/event.tab.gz"):
    os.remove("/tmp/event.tab.gz")

preprocess.create_event_file(
    corpus_file="/tmp/corpus.txt",
    event_file="/tmp/event.tab.gz",
    context_structure='document',
    event_structure='consecutive_words',
    event_options=(1, ),
    cue_structure='bigrams_to_word'
)
```

### What actually happened

```
$ cat /tmp/event.tab
cues	outcomes
#m_t#_it_mi	mit
#m_ik_k#_mi	mik
#m_n#_mi_in	min
#m_ks_mi_ik_si_i#	miksi
```

### What I expected to happen

```
$ cat /tmp/event.tab
cues	outcomes
#m_tä_it_mi_ä#	mitä
#m_ik_kä_mi_ä#	mikä
#m_ä#_mi_in_nä	minä
#m_ks_mi_ik_si_i#	miksi
```

### System details

```
Pyndl Information
=================

General Information
-------------------
Python version: 3.9.13
Pyndl version: 0.8.2

Operating System
----------------
OS: Linux x86_64
Kernel: 5.10.0-10-amd64
CPU: 8
Mem: 6461MiB/19700MiB
Swap: 0MiB/28355MiB

Dependencies
------------
numpy: 1.23.0
scipy: 1.6.1
cython: 0.29.30
pandas: 1.4.3
xarray: 2022.3.0
netCDF4: 1.6.0
pip: 21.3.1
packaging: 21.3
```

I'm a bit confused about this issue since in the JOSS paper UTF-8 is mentioned quite a bit, as well as previous studies that have successfully used the software with languages which use extended Latin. Could this be a user error somehow?

**Comment by derNarr** [comment]
I fully agree that your expectations are completely sane and ``pyndl`` behaviour is not meeting your expectations.

Still the following code would achieve what you want to do:

```
from pyndl import preprocess

CORPUS = """
mitä
mikä
minä
miksi
""".strip()

with open("/tmp/corpus.txt", "w") as f:
    f.write(CORPUS)

if os.path.exists("/tmp/event.tab.gz"):
    os.remove("/tmp/event.tab.gz")

preprocess.create_event_file(
    corpus_file="/tmp/corpus.txt",
    event_file="/tmp/event.tab.gz",
    symbols='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZä',
    context_structure='document',
    event_structure='consecutive_words',
    event_options=(1, ),
    cue_structure='bigrams_to_word'
)
```

For some reason we introduced a ``symbols`` parameter in ``preprocess.create_event_file`` that defaults to ascii characters only. Even if the desired behaviour can be achieved by adding the desired symbol to the ``symbols`` parameter, I will check on how to solve this so that the function defaults to allow all characters except for ``\t``, ``_``, and ``#``.

**Comment by frankier** [comment]
Okay. I see now that `symbols` is used to do a quick tokenisation of the string. Just to note that this is something that users may like to plug into and combine with external libraries (e.g. nltk, special word segmentation for CJK languages). For extracting word-like characters `\w` in regex or `isalnum()` on string are usually sufficient.

**Comment by frankier** [comment]
Also rather than specifying symbols manually users might like to e.g. provide a function which can then return true or false given a character. As an example of how this could help, it would help with filtering using data from `unicodedata` (See https://unicodebook.readthedocs.io/unicode.html#categories )

**Comment by derNarr** [comment]
Hopefully, our changes fix this issue and prevent other new users to run into the same problem.

For more complex tokenization tasks it is strongly advised to create an event file by hand. In the end, the event file is a tab separated two column table file, where in each column different cues or outcomes are separated by an underscore. Depending on the source files this is two `'_'.join(...)` and one `data.to_csv('path_to_event_file.tab.gz', sep='\t')` line of code.

But feel free to reopen this issue, if there are still concerns left.
