### ISSUE TITLE
Explain usage of grapheme clusters with non-western languages

### ISSUE THREAD

**Issue by dekuenstle** [quantling/pyndl#228]
@frankier raised questions about how to use grapheme clusters, e.g. with Chinese characters, in pyndl.

We should stress in the documentation and the JOSS paper, that in this case the Chinese characters should already be preprocessed (by any other software) ––pyndl expects to deal with grapheme-like content (e.g. radicals in this case).

See [frankier's description](https://github.com/openjournals/joss-reviews/issues/4515):

> In my attempts to test the functional claims of the paper, I came across this issue https://github.com/quantling/pyndl/issues/220 . This got me thinking as to how well the package deals with Unicode in general. In particular, with things like extracting bigrams, the most reasonable thing to may most usually be to work with grapheme clusters. Note this is different from code points, which is what you will get if you work with Python 3/unicode strings directly -- if you are working with code points then you should probably switch to grapheme clusters. It might not really make sense to extract bigrams with e.g. Chinese characters as whole grapheme clusters but rather to decompose them into radicals. I'm not sure what to do about this except for document what you are doing at the moment or add some kind of caveats section to the documentation and note that multilinguality is a bit of an open box in the paper, underlining that support for ideograms / pictograms / logograms is not really there. I do think this is somewhat important given the emphasis on multilinguality in the paper.

**Comment by derNarr** [comment]
The main underlying misunderstanding seems to be that a major focus of `pyndl` is on the clever creation of cues and outcomes for different languages that can be learned with naive disciminative learning. From our point of view the main focus is on implementing the learning itself in an efficient way and the preprocessing of the best inputs (cues) and outputs (outcomes) should be done with another software.

**Comment by frankier** [comment]
I agree that it is reasonable to decide that text processing and cue creation is out of scope of the library. However, if you take the position that the library is really only about learning, then the paper need not put any particular emphasis on UTF-8 support, since this primes people to think that good support of different writing systems is a major aim of the library. There might be some in-between position you can take here too.

**Comment by derNarr** [comment]
Besides that it is easier to maintain and explore different variants of the RW learning rule in a Python/Cython library compared to a R/Rcpp/C++ library one of the major drawbacks of the `ndl2` library is its poor support for Unicode. Therefore, one of my main selling point to people, who used `ndl2` in their research is/was the improved Unicode support in the `pyndl` package.

But I see now, that this emphasis only makes sense in the context of having the poor Unicode support in R and `ndl2` but gives the wrong suggestions to someone used to Python3, where Unicode strings became a language feature and therefore is not really worth mentioning anymore.

I am still a bit puzzled on how to properly address these two audiences. The one audience coming from Python3, who are rightfully underwhelmed that `pyndl` can use Unicode and in contrast the audience coming from R and `ndl2` for whom this might be a good reason to switch to a different programming language.

I will try to make this in-between position more clear and transparent. @frankier if you have any suggestions, I am happy to hear about them as well :-)

**Comment by derNarr** [comment]
We reformulated one paragraph in the paper to:

> The input to *pyndl* is agnostic to the actual domain as long as it is
> tokenized as Unicode character strings. Input sequences can consist of multiple
> tokens separated by underscores which is together with the tab-character the
> only special character in *pyndl*. While *pyndl* provides some basic
> preprocessing for grapheme tokenization, the preprocessing of ideograms,
> pictograms, logograms, and speech is possible using custom preprocessing. For
> example, word classification using tokenized speech audio recordings was
> investigated in @Arnold_2017. Inputs in this work consisted of around 50 tokens
> per time slice, where each token encoded the pitch, loudness, and variability
> into a string.

Hopefully, this makes the use-case for `pyndl` more clear and showcases what is possible and what is not.
