### ISSUE TITLE
events from DataFrame

### ISSUE THREAD

**Issue by Trybnetic** [quantling/pyndl#44]
Instead of reading events from an event_file it could also be useful to generate them from a pandas DataFrame.

Either by generating it directly or by using a tempfile.

**Comment by dekuenstle** [comment]
Probably we should just generalize this issue to: pyndl.ndl.ndl accept event generator. (Similar to pyndl.ndl.dict_ndl and pyndl.activation.activation)
@Trybnetic does this make sense?
