### ISSUE TITLE
write example

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#5]
Write an example which covers

- [x] create event file out of corpus file
- [x] count cues and outcomes
- [x] clean (filter) events based on the counts
- [x] learn weights of cleaned events
- [x] save weight matrix
- [x] load weights into R

- [x] load weight matrix
- [x] continue learning
- [x] save weight matrix

**Comment by Trybnetic** [comment]
- [ ] write example for activation

**Comment by Trybnetic** [comment]
@dekuenstle @derNarr @sumny Should we probably make an issue per point?

Because for some points like testing examples there is already an issue (#48).

**Comment by Trybnetic** [comment]
> - [ ]  fancy IPython notebook examples?

With #131 I made an extra issue out of this point, as I think this point is worth its own discussion

**Comment by Trybnetic** [comment]
I think we can close this issue with the proposed changes in #112 and the open issues #131 and #132 for the remaining points.
