### ISSUE TITLE
fix travis

### ISSUE THREAD

**Issue by Trybnetic** [quantling/pyndl#66]
travis does not find our repository any more and I am not sure why.

I looked it up some days ago and the access rights for quantling were removed. I granted the rights again but the repository does not show up on travis any more. 
@dekuenstle @derNarr has one of you changed something in the repository settings or has any idea why travis does not work anymore?

I think we should fix this asap!

**Comment by dekuenstle** [comment]
It's just the link i think! Private projects are travis-ci.com. Public travis-ci.org . But took me some time to find this -.-
