### ISSUE TITLE
Improve alpha attribute string for dict_ndl 

### ISSUE THREAD

**Issue by dekuenstle** [quantling/pyndl#73]
When using dict_ndl, the alpha value is a defaultdict (or we create one). 
The attrs string therefore becomes

>  "defaultdict(<function dict_ndl.<locals>.<lambda> at 0x7fcc57507268>, {'a': 0.1, 'b': 0.1, 'c': 0.1})"

This is alreadyy ugly and will get worse with more given cues.

If the user just inputs a float as alpha we should just pass this float, and not the defaultdict we create, to the attrs function. 
But what should we print for a dict? A place holder ("varying") or the values of 3 cues? 
@derNarr @Trybnetic

**Comment by derNarr** [comment]
It would be reasonable to store the float into the attrs function and if a defaultdict is supplied "varying" would be a good place holder.
