### ISSUE TITLE
harmonize API of `dict_ndl` and `ndl`

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#75]
Make the `dict_ndl` and the `ndl` function look more similar in terms of the parameters used in the function.

**Comment by dekuenstle** [comment]
according to SemVer this would be a non-compatible API change, so we should increase the MAJOR version

**Comment by derNarr** [comment]
As long as we are in alpha I consider a minor version jump (i. e. 0.2.x -> 0.3.x) as a major version jump and a patch increase (i. e. 0.2.1 -> 0.2.2) as a minor increase (without breaking the API).

We should definitely follow SemVer after releasing 1.0.0.

**Comment by dekuenstle** [comment]
pyndl.ndl.ndl returns dimensions ('outcomes', 'cues'), but docstring tells opposite.
In general we should harmonize  ndl/dict_ndl also with activation.

**Comment by derNarr** [comment]
We kept the difference in `alpha` and `alphas`.
