### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#80]
- [x] mention readthedocs.io in the readme
- [x] rework install describtion
- [x] create a CONTRIBUTE.rst
- [x] move terminology to doc/

**Comment by dekuenstle** [comment]
We should also try following the README structure which is quasi-standard on github: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by derNarr** [comment]
Most of the changes are incorporated into pull request #77
