### ISSUE TITLE
official macos support

### ISSUE THREAD

**Issue by dekuenstle** [quantling/pyndl#82]
While #76 adds macos install instructions to the readme, we're not officially support it yet according to the package and tests. 

- [ ] add macos tags to setup.py
- [ ] autotest on macos via travis
- [ ] extend readme (could also be fulfilled with #76 and #80)
- [ ] check for gcc >=6.3 on install and give hint

**Comment by derNarr** [comment]
comment from Cyrus:

> Can you have setup.py check for a good compiler on Mac OS X and complain if
> gcc is aliased to clang?

He did the following in an Anaconda environment in order to get it working under Mac OS X:

```
I then installed GCC 6.3.0 on my Mac, and then did this:

> export CC=/usr/local/bin/gcc-6
> pip install pyndl
```

**Comment by Trybnetic** [comment]
Travis provides no pre-installed python. Either we have to find another way to install python, gcc, ... or we have to use another CI for macOS.

Can probably someone with a Mac create an install script?

**Comment by Trybnetic** [comment]
I have figured out that some other projects use [pyenv](https://github.com/pyenv/pyenv) to manage the python version on travis' macos builts (e.g. [simplejson](https://github.com/simplejson/simplejson)).

I will check that out further when I have more time again..
