### ISSUE TITLE
Leaving alpha version package state

### ISSUE THREAD

**Issue by dekuenstle** [quantling/pyndl#83]
According to our README and package classifier we are still in alpha state. 
We should think about what's necessary to continue to a beta or stable state and increase version to 1.0. 

- [x] good README #80 
- [x] stable API #75
- [ ] linux + macos support #82

What else is necessary in your oppinion? Are there any other parts of API which we have to clean?

**Comment by derNarr** [comment]
API changes I would like to do:

* [ ] `number_of_threads` / `number_of_precesses` -> `n_jobs` (as in scikit-learn)
* [ ] `event_path` / `event_list` -> `events` while renaming the function `ndl.events` to `ndl.events_from_file`

oder changes?

**Comment by Trybnetic** [comment]
I think we should use a milestone instead of this issue. What do you think?

**Comment by Trybnetic** [comment]
I close this due to duplicate issues as mentioned in the description and will add a milestone for this!
