### ISSUE TITLE
error code -1160725808

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#85]
Occasionally, the following bug appears. No idea so far what is the reason for it.

```
File "pyndl/ndl_parallel.pyx", line 65, in pyndl.ndl_parallel.learn_inplace (pyndl/ndl_parallel.c:2085)
OSError: binary files does not have proper format, error code -1160725808
```

**Comment by dekuenstle** [comment]
Is there a specific dataset you get that error with?

**Comment by dekuenstle** [comment]
I'm not much into cython, but spme things were unexpected for me. Still they don't directly explain that error code.

```Cython
    for binary_file_path in binary_file_paths: #
      filename_byte_string = binary_file_path.encode("UTF-8")
      fname = filename_byte_string

      number_parts = (length_all_outcomes // chunksize) + 1

      with nogil, parallel(num_threads=number_of_threads):
        for ii in prange(number_parts, schedule="dynamic", chunksize=1):
          start_val = ii * chunksize
          end_val = min(start_val + chunksize, length_all_outcomes)
          if start_val == length_all_outcomes:
            break
          error = 0
          error = learn_inplace_ptr(fname, weights_ptr, mm, alpha, beta1,
                            beta2, lambda_, all_outcomes_ptr, start_val,
                            end_val)
    if (error != 0):
        raise IOError('binary files does not have proper format, error code %i' % error)
```

1. Indents are mixed 2 and 4 spaces. cpython3 would complain. Cython doesnt?
2. error is first used and written in a threaded / parallel context but read outside. 
    Is error some kind of shared memory variable written in multiple threads, or is there one error variable per thread?
    Is this really a valid, threadsafe operation?
3. We check for an error outside the parallel and the file for-loop. For me it seems, like we just check what the slowest/last thread has written. Shouldn't we check for errors in each binary file?

@Trybnetic what do you say?

**Comment by Trybnetic** [comment]
> 1. Indents are mixed 2 and 4 spaces. cpython3 would complain. Cython doesnt?  

I don't think so. Even though we should make it consistent

But I'm not sure why we don't raise errors immediately instead of returning error codes? @derNarr do you remember why we do this error code stuff? 

I've also tried whether the error occurs due to too large binary files. But reducing the events_per_file which leads to smaller but therefore more binary event files does not help.

**Comment by Trybnetic** [comment]
Another interesting (and even more confusing) thing is that the error does not occur while using the threading method which also uses the binary format..

**Comment by Trybnetic** [comment]
First I assumed the error in the temporary directory as this was our last major change there. But given that threading works with the binary files but openmp does not lead me suppose that the error is elsewhere.

An important difference between threading and openmp is that slicing all_outcomes is done in ndl.py in the threading version but in the ndl_parallel.pyx in the openmp method. I'm still not sure how this could cause the error but it is in my opinion the most likely part.

**Comment by dekuenstle** [comment]
@Trybnetic what do you say about my points 2 and 3 above? Maybe openmp has some writing problems to shared vars, which we don't run into with threads.

**Comment by derNarr** [comment]
Finally, a reply be me:

1. We should make the indentation consistent.
2. & 3. Within a "nogil" context we can only use a very reduced python subset. We cannot raise an error in that context as far as I know. But we should be able to break the loop when an error code is non-zero. Every assignment within the for loop should be thread safe (no race conditions), but as the code is, we only get the last error code.
