### ISSUE TITLE
check for correct input in activation

### ISSUE THREAD

**Issue by Trybnetic** [quantling/pyndl#86]
Check in activation whether the weight matrix has the correct dimensions and raise a ValueError if not

**Comment by dekuenstle** [comment]
If we start doing input validation for the matrices (instead of following "ask for forgiveness not permission"), we should do the very same checks for ndl as well.

**Comment by Trybnetic** [comment]
This issue comes mostly from the inconsistency between activation.py and ndl.py which should be fixed by #87.

**Comment by Trybnetic** [comment]
Besides, ndl raises a ValueError if you pass a a transposed weight matrix. Activation didn't raise one.
