### ISSUE TITLE
reduce memory overhead in activation.py

### ISSUE THREAD

**Issue by Trybnetic** [quantling/pyndl#88]
As we only need weights in activation.py to get values from it we can share it between the threads.
Therefore, we should do it like ndl.py and use cython to make it probably more faster and at least less memory expensive

**Comment by dekuenstle** [comment]
The weight and activation matrices are currently shared between the processes. 
Doesn't this work for you, so you get a linear increase of memory for increasing number of processes, in quantity of the matrices memory?

**Comment by Trybnetic** [comment]
> The weight and activation matrices are currently shared between the processes.

Yes, and this is in my opinion not a good solution. Shared matrices would be much better and do not have the memory increase

**Comment by Trybnetic** [comment]
Sorry, issue was not necessary. The matrix is already shared. Memory overhead was due to another function which is not in pyndl
