### ISSUE TITLE
Define dependency versions

### ISSUE THREAD

**Issue by dekuenstle** [quantling/pyndl#90]
We should explicitly define a fixed (==) version for every dependency in the requirements (pip) and dev requirements (tox) because

1. it avoids broken builds due to some (api) changes in a dependency. We ran into this recently.
2. we target science. A fixed version of pyndl should produce reproducable results. If the dependency versions can be different for the same pyndl version it's unlikely.

**Comment by derNarr** [comment]
Draw back would be, that we need to update the dependencies, after each major release (minor?).

To 2.): The test suit should keep pyndl in a reproducible state. Would you disagree?

**Comment by Trybnetic** [comment]
I agree with @dekuenstle as the update of pylint was very confusing and we had to spent a lot of time fixing it. Hence, I would fix the versions and monitor updates for example with https://requires.io/

**Comment by Trybnetic** [comment]
We should use lower bounds and monitor the dependencies
