### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#91]
Hi, there is a number of related projects especially for the preprocessing:

* https://textblob.readthedocs.io/en/dev/
* http://www.nltk.org/
* http://www.clips.ua.ac.be/pages/pattern-en
* https://radimrehurek.com/gensim/
* https://github.com/the-new-sky/Kadot/blob/master/README.md

Do we want to incorporate some of these functionalities?

Do we want to have documentation how to use them in conjunction?

Do we want to have a list of projects that could be of direct interest to pyndl users?

**Comment by dekuenstle** [comment]
We can mention related/useful Projects in readme.
I prefer extending the docs with examples we come up in real world application.

**Comment by derNarr** [comment]
In the last years, this topic never came up. And adding these references without having a concrete example and test cases runs into the risk of getting outdated therefore I will not add these references for now. If someone adds an example, which uses a third party library in a meaningful way, I am happy to link this in the documentation together with the example.
