### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#99]
The following comments from @dekuenstle need to be adressed:

- [ ] The general structure of the examples section is a bit confusing. We may want to differenciate better by moving to subpages between general example/explanation of discrimination learning, the module usage examples and minimal working examples (including data preprocessing and evaluation)
- [ ] heading `pyndl.preprocess module` in `example.rst` Rendered font looks like heading, but according to the text it should be just emphasised
- [ ] in `comparison_of_algorithms.rst` add description of formula items too in table
- [ ] add entry point of docu to *README* as `doc/build/html/index.html`
- [ ] The doc is not build on install. We may add the compile step to the install script, or explain here how to build the docs

**Comment by Trybnetic** [comment]
I deleted 

> "Should the references stay like this ``[@rescorlawagner1972]``? (probably not)" 

as it should be resolved more in general with #115
